SELECT distinct ?object ?title
WHERE {

     ?dig  ecrm:P129_is_about ?prd .
     ?prd ecrm:P108_has_produced ?object .
     ?object a ecrm:E22_Man-Made_Object .
 
 optional {?object ecrm:P102_has_title ?title }

        {?prd ecrm:P126_employed <http://data.silknow.org/vocabulary/628>, <http://data.silknow.org/vocabulary/368>, <http://data.silknow.org/vocabulary/644>  .}      
}

