PREFIX od:    <http://data.odeuropa.eu/ontology/>
PREFIX crm:   <http://erlangen-crm.org/current/>
PREFIX time:  <http://www.w3.org/2006/time#>

# What smell source have the highest number of documentation in [time, e.g. 18th centuries]?

SELECT ?source COUNT(DISTINCT ?experience)
WHERE {
  ?emission od:F3_had_source / crm:P137_exemplifies ?source ;
            od:F1_generated ?smell .

  ?experience od:F2_perceived ?smell;
            time:hasTime / time:inXSDDate ?time.

  FILTER ( ?time >= "1701"^^xsd:gYear AND ?time <= "1800"^^xsd:gYear )
}
GROUP BY ?source
ORDER BY DESC(COUNT(DISTINCT ?emission))
