PREFIX od:    <http://data.odeuropa.eu/ontology/>
PREFIX crm:   <http://erlangen-crm.org/current/>
PREFIX time:  <http://www.w3.org/2006/time#>

# When a [specific odour] started to be mentioned in text?

SELECT ?source MIN(?time)
WHERE {
  ?emission od:F3_had_source / crm:P137_exemplifies ?source;
            od:F1_generated ?smell .

  ?experience od:F2_perceived ?smell;
            time:hasTime / time:inXSDDate ?time.

  VALUES ?source { <http://data.odeuropa.eu/vocabulary/olfactory-objects/230> }
  # 230 = Tar
}
