PREFIX od:    <http://data.odeuropa.eu/ontology/>
PREFIX crm:   <http://erlangen-crm.org/current/>
PREFIX time:  <http://www.w3.org/2006/time#>
PREFIX reo:  <https://read-it.acc.hum.uu.nl/ontology#>

# Which smelling gestures have been more described in [profession, e.g. tea-merchants]’ experiences?

SELECT ?gesture DESC(COUNT(DISTINCT ?experience))
WHERE {
  ?experience a od:L13_Olfactory_Experience;
          od:F5_involved_gesture ?gesture ;
          crm:P14_carried_out_by / reo:readP1_has_occupation "tea merchant" .
}
GROUP BY ?gesture
ORDER BY DESC(COUNT(DISTINCT ?experience))
