PREFIX od:    <http://data.odeuropa.eu/ontology/>
PREFIX crm:   <http://erlangen-crm.org/current/>
PREFIX time:  <http://www.w3.org/2006/time#>
PREFIX reo:  <https://read-it.acc.hum.uu.nl/ontology#>

# Which flavours are associated with [topic, e.g. femininity] in [Asia]?

SELECT ?source
WHERE {
  ?emission od:F3_had_source / crm:P137_exemplifies ?source ;
            od:F1_generated ?smell .

  ?experience od:F2_perceived ?smell;
              od:evoked "femininity"@en .


  {
    ?emission crm:P8_took_place_at ?place .
  } UNION {
    ?emission crm:P8_took_place_at / crm:P89_falls_within* ?place .
  }

  VALUES ?place {"Asia"}
}
