PREFIX od:    <http://data.odeuropa.eu/ontology/>
PREFIX crm:   <http://erlangen-crm.org/current/>
PREFIX time:  <http://www.w3.org/2006/time#>
PREFIX reo:   <https://read-it.acc.hum.uu.nl/ontology#>
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>

# What scents do [named, country of origin, male/female] authors describe most?

SELECT DISTINCT ?sex ?source COUNT(DISTINCT ?smell)
WHERE {
  ?emission a od:L12_Smell_Emission ;
            od:F3_had_source / crm:P137_exemplifies ?source ;
            od:F1_generated ?smell .

  ?text a crm:E33_Linguistic_Object ;
      schema:author ?author ;
      crm:P67_refers_to ?smell .

  ?author foaf:gender ?sex
  # todo country
}
GROUP BY ?sex ?source
ORDER BY COUNT(DISTINCT ?smell)
