PREFIX od:    <http://data.odeuropa.eu/ontology/>
PREFIX crm:   <http://erlangen-crm.org/current/>
PREFIX time:  <http://www.w3.org/2006/time#>
PREFIX reo:   <https://read-it.acc.hum.uu.nl/ontology#>
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>

# What sort of people react to smells in paintings?

SELECT DISTINCT ?occupation ?sex ?group ?age COUNT(DISTINCT ?gesture)
WHERE {
  ?experience a od:L13_Olfactory_Experience;
          od:F2_perceived ?smell ;
          od:F5_involved_gesture ?gesture ;
          crm:P14_carried_out_by ?person .

  OPTIONAL { ?person reo:readP1_has_occupation ?occupation }
  OPTIONAL { ?person foaf:gender ?sex ?occupation }
  OPTIONAL { ?person reo:readP25_is_member_of ?group }
  OPTIONAL { ?person foaf:age ?age }

  ?work a crm:crm:E36_Visual_Item ;
      crm:P67_refers_to ?smell .
}
GROUP BY ?occupation ?sex ?group ?age
