PREFIX od:    <http://data.odeuropa.eu/ontology/>
PREFIX crm:   <http://erlangen-crm.org/current/>
PREFIX time:  <http://www.w3.org/2006/time#>
PREFIX reo:   <https://read-it.acc.hum.uu.nl/ontology#>

# Which time [century, decade] was portraying more smell?

SELECT DISTINCT ?century COUNT(DISTINCT ?work)
WHERE {
  ?work a crm:crm:E36_Visual_Item ;
      schema:dateCreated / time:hasBeginning ?time ;
      crm:P67_refers_to ?smell .

  BIND(SUBSTR(?time, 0, 2) AS ?century)
}
GROUP BY ?century
ORDER BY DESC(COUNT(DISTINCT ?work))
